spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: create-drop
      use-new-id-generator-mappings: false
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.default_batch_fetch_size: 30
  datasource:
    url: jdbc:h2:tcp://localhost/~/soloProject
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  redis:
    host: localhost
    port: 6379
cloud:
  aws:
    s3:
      bucket:
        url:
        name:
    credentials:
      instance-profile: true
      accessKey: accessKey
      secretKey: secretKey
    region:
      static: ap-northeast-2
    stack:
      auto: false

jwt:
  secretKey: teststestssdfstsset